ifndef DESTDIR
DESTDIR=/usr/
endif
ifndef CONFDIR
CONFDIR=/etc
endif

# generated by looking at rpm -ql on the mlnx-en-utils rpm
USERSPACE_TOOLS= \
	mlnx_eswitch_set            \
	sysctl_perf_tuning          \
	mlnx_dump_parser            \
	mlnx_get_vfs.pl             \
	mlnx_perf                   \
	mlnx_qcn                    \
	mlnx_qos                    \
	mlx_fs_dump                 \
	tc_wrap.py                  \
	common_irq_affinity.sh      \
	mlnx_tune                   \
	set_irq_affinity.sh         \
	set_irq_affinity_bynode.sh  \
	set_irq_affinity_cpulist.sh \
	show_irq_affinity.sh        \
	show_irq_affinity_hints.sh

install:
	install -v -m 644 mellanox-lib.sh $(DESTDIR)/lib/kvc/
	install -v -m 644 mellanox.conf $(CONFDIR)/kvc/
	install -v -m 755 mellanox-wrapper.sh $(DESTDIR)/lib/kvc/
	for tool in $(USERSPACE_TOOLS); do \
		ln -sf ../lib/kvc/mellanox-wrapper.sh $(DESTDIR)/bin/$${tool}; \
	done
