# generated by looking at rpm -ql on the mlnx-en-utils rpm
USERSPACE_TOOLS= \
	mlnx_eswitch_set            \
	sysctl_perf_tuning          \
	mlnx_dump_parser            \
	mlnx_get_vfs.pl             \
	mlnx_perf                   \
	mlnx_qcn                    \
	mlnx_qos                    \
	mlx_fs_dump                 \
	tc_wrap.py                  \
	common_irq_affinity.sh      \
	mlnx_tune                   \
	set_irq_affinity.sh         \
	set_irq_affinity_bynode.sh  \
	set_irq_affinity_cpulist.sh \
	show_irq_affinity.sh        \
	show_irq_affinity_hints.sh

install:
	sudo install -v -m 644 host/usr/local/lib/kvc-mellanox-lib.sh /usr/local/lib/
	sudo install -v -m 644 host/etc/kvc-mellanox.conf /etc/
	sudo install -v -m 755 host/usr/local/bin/kvc-mellanox-wrapper.sh /usr/local/bin/
	for tool in $(USERSPACE_TOOLS); do sudo ln -sf ./kvc-mellanox-wrapper.sh /usr/local/bin/$${tool} ; done
